### ISSUE TITLE
frda_all_sim.onnx，from ？

### ISSUE THREAD

**Issue by zhongwenkun886** [Star-Clouds/FRDA#1]
hi，very great job！
Is the model (frda_all_sim.onnx) from the other open source project ? or was it  trained by yourself?

**Comment by ywlife** [comment]
> hi，very great job！
> Is the model (frda_all_sim.onnx) from the other open source project ? or was it trained by yourself?

Yes, I trained frda net and transformed to onnx format.

**Comment by zhongwenkun886** [comment]
Great!
will you open your train source code later?
and which paper this project reference to?
thanks

**Comment by ywlife** [comment]
> Great!
> will you open your train source code later?
> and which paper this project reference to?
> thanks

Currently, there are no plans.  
You can refer to 3DMM, PRNet, DenseReg and son on.
